import { ViewTypes } from "./view-types.enum"

export interface AgentReport {
        timePeriod: ViewTypes,
        reportId: string,
        startDate: number,
        endDate: number,
        userId: string,
        userFullName: string,
        totalChats: number,
        avgChatHandleTime: number,
        avgChatDuration: number,
        totalCalls: number,
        totalInbound: number,
        totalOutbound: number,
        avgVoiceHandleTime: number,
        avgVoiceHoldTime: number,
        totalCallsAndChats: number,
        averageIdleTime: number,
        utilizationPercent: number,
        avgAfterContactWorkTime: number,
        missedContacts: number,
        answerRate: number,
        avgChatRating: number,
        avgVoiceRating: number,
        avgVoiceChatRating: number,
        chatRatingCount: number,
        voiceRatingCount: number,
        voiceChatRatingCount: number,
        totalEmailCount: number,
        avgEmailResponse: number,
        totalSmsCount: number,
        avgSmsResponse: number,
        overdueTicketCount: number,
        totalTicketsCount: number,
}